---
layout: page
title: Publications
---

<div class="navbar">
    <div class="navbar-inner">
        <ul class="nav">
            <li><a href="#articles">Journal Articles</a></li>
            <!--
            <li><a href="#conferences">Conferences</a></li>            
            -->
        </ul>
    </div>
</div>


```{r setup, include = FALSE}
opts_chunk$set(echo = FALSE, cache = FALSE, tidy = FALSE, warning = FALSE, message = FALSE)
opts_knit$set(upload.fun = identity)
```

```{r}
library(RefManageR)
```

```{r}
bopts <- BibOptions(check.entries = FALSE)
```

```{r}
print_bib <- function(bib)
{
  print(bib, .opts = list(sorting = 'ydnt', max.names = 20, no.print.fields = c("url"))) # sort by year, descending, then name, title
}

read_bib <- function(file) 
{
  ReadBib(file)  
}
```

### <a name="articles"></a>Journal Articles

Source: [ncbi.nlm.nih.gov/pubmed?term=soria,%20jose%20manuel](http://www.ncbi.nlm.nih.gov/pubmed?term=soria,%20jose%20manuel&cmd=correctspelling).


```{r}
#articles <- read_bib("bib/articles.bib")
articles <- read_bib("bib/articles.pubmed.bib")
```

#### 2012 --- 2016

```{r print_articles, results = "asis"}
print_bib(articles[list(year = "2012/2016")])
```

#### * --- 2011

```{r print_articles_2, results = "asis"}
print_bib(articles[list(year = "/2011")])
```

```{r}
#conferences <- read_bib("bib/conferences.bib")
```

```{r print_conf, results = "asis"}
#print_bib(conferences)
```

